### ISSUE TITLE
practica 5

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-con-sonarcloud-entrevista-ar#1]
[Sonarcloud.pdf](https://github.com/SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-con-sonarcloud-entrevista-ar/files/9670030/Sonarcloud.pdf)

**Comment by Lizzetee** [comment]
Calificación: 19

**Comment by josealfredo79** [comment]
Falto agregar las actividades segun moprosoft

**Comment by josealfredo79** [comment]
@bg55-a favor de revisar bien...

**Comment by josealfredo79** [comment]
Revisado

**Comment by josealfredo79** [comment]
Calificacion: 16
